name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Check module vendoring
      run: |
        go mod tidy
        go mod vendor
        go mod verify
        test -z "$(git status --porcelain)" || (echo "please run 'go mod tidy && go mod vendor', and submit your changes"; exit 1)

    - name: Cache LLVM and Clang
      id: cache-llvm
      uses: actions/cache@fd5de65bc895cf536527842281bea11763fefd77
      with:
        path: $HOME/.clang
        key: llvm-12.0

    - name: Install LLVM and Clang
      uses: KyleMayes/install-llvm-action@ef175530927af66c61e4e8da4fea4e15de63f780
      with:
        ubuntu-version: "20.04"
        version: "12.0.0"
        directory: $HOME/.clang
        cached: ${{ steps.cache-llvm.outputs.cache-hit }}

    - name: Generate
      run: go generate .

    - name: Build
      run: go build .
